server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;

    location = /healthz {
        default_type application/json;
        return 200 '{"status":"OK","service":"pulse-frontend"}';
    }

# Activate this section if you want to enable OpenTelemetry metrics collection for the frontend service.
#    location /otlp-http/ {
#        proxy_pass http://otel-collector:4318/;
#        proxy_set_header Host $host;
#    }

    location / { try_files $uri $uri/ /index.html; }
}
