version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofumpt
    - misspell
    - revive

  settings:
    revive:
      severity: warning

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  