# Identifiants SonarCloud
sonar.organization=jasonouellet
sonar.projectKey=jasonouellet_pulse
sonar.projectName=Project PULSE
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

# Analyse du code et des tests
sonar.sources=internal,pkg,cmd,frontend/src
sonar.tests=internal,frontend/src
sonar.test.inclusions=**/*_test.go,**/*.test.tsx,**/*.test.ts,**/*.spec.ts,**/*.spec.tsx
sonar.exclusions=**/vendor/**,**/node_modules/**,**/docs/**,**/*.d.ts

# Rapports de couverture
sonar.go.coverage.reportPaths=coverage-go.out
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
