# Identifiants SonarCloud
sonar.organization=jasonouellet
sonar.projectKey=jasonouellet_pulse
sonar.projectName=Project PULSE
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

# Analyse du code et des tests
sonar.sources=internal,pkg,cmd,frontend/src
sonar.tests=internal,frontend/src
sonar.test.inclusions=**/*_test.go,**/*.test.tsx,**/*.test.ts,**/*.spec.ts,**/*.spec.tsx

# Exclusions (exclut le code généré sqlc pour ne pas fausser le score de couverture)
sonar.exclusions=**/vendor/**,**/node_modules/**,**/docs/**,**/*.d.ts,internal/core/adapters/postgres/db/**,**/*.gen.go

# Rapports de couverture (Go + Frontend)
sonar.go.coverage.reportPaths=coverage-go.out
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

# Rapports d'exécution des tests unitaires (Go + Frontend)
sonar.go.tests.reportPaths=report-go.xml
sonar.testExecutionReportPaths=frontend/test-report-frontend.xml