// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CoreGenderCategory string

const (
	CoreGenderCategoryMASCULINE CoreGenderCategory = "MASCULINE"
	CoreGenderCategoryFEMININE  CoreGenderCategory = "FEMININE"
	CoreGenderCategoryMIXED     CoreGenderCategory = "MIXED"
)

func (e *CoreGenderCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoreGenderCategory(s)
	case string:
		*e = CoreGenderCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for CoreGenderCategory: %T", src)
	}
	return nil
}

type NullCoreGenderCategory struct {
	CoreGenderCategory CoreGenderCategory `json:"core_gender_category"`
	Valid              bool               `json:"valid"` // Valid is true if CoreGenderCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoreGenderCategory) Scan(value interface{}) error {
	if value == nil {
		ns.CoreGenderCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoreGenderCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoreGenderCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoreGenderCategory), nil
}

type CoreOrganizationType string

const (
	CoreOrganizationTypeCLUB        CoreOrganizationType = "CLUB"
	CoreOrganizationTypeASSOCIATION CoreOrganizationType = "ASSOCIATION"
	CoreOrganizationTypeFEDERATION  CoreOrganizationType = "FEDERATION"
)

func (e *CoreOrganizationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoreOrganizationType(s)
	case string:
		*e = CoreOrganizationType(s)
	default:
		return fmt.Errorf("unsupported scan type for CoreOrganizationType: %T", src)
	}
	return nil
}

type NullCoreOrganizationType struct {
	CoreOrganizationType CoreOrganizationType `json:"core_organization_type"`
	Valid                bool                 `json:"valid"` // Valid is true if CoreOrganizationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoreOrganizationType) Scan(value interface{}) error {
	if value == nil {
		ns.CoreOrganizationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoreOrganizationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoreOrganizationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoreOrganizationType), nil
}

type CoreRegistrationStatus string

const (
	CoreRegistrationStatusPENDING  CoreRegistrationStatus = "PENDING"
	CoreRegistrationStatusASSIGNED CoreRegistrationStatus = "ASSIGNED"
)

func (e *CoreRegistrationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoreRegistrationStatus(s)
	case string:
		*e = CoreRegistrationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CoreRegistrationStatus: %T", src)
	}
	return nil
}

type NullCoreRegistrationStatus struct {
	CoreRegistrationStatus CoreRegistrationStatus `json:"core_registration_status"`
	Valid                  bool                   `json:"valid"` // Valid is true if CoreRegistrationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoreRegistrationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CoreRegistrationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoreRegistrationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoreRegistrationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoreRegistrationStatus), nil
}

type CoreRelationshipType string

const (
	CoreRelationshipTypeMOTHER        CoreRelationshipType = "MOTHER"
	CoreRelationshipTypeFATHER        CoreRelationshipType = "FATHER"
	CoreRelationshipTypeLEGALGUARDIAN CoreRelationshipType = "LEGAL_GUARDIAN"
	CoreRelationshipTypeOTHER         CoreRelationshipType = "OTHER"
)

func (e *CoreRelationshipType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoreRelationshipType(s)
	case string:
		*e = CoreRelationshipType(s)
	default:
		return fmt.Errorf("unsupported scan type for CoreRelationshipType: %T", src)
	}
	return nil
}

type NullCoreRelationshipType struct {
	CoreRelationshipType CoreRelationshipType `json:"core_relationship_type"`
	Valid                bool                 `json:"valid"` // Valid is true if CoreRelationshipType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoreRelationshipType) Scan(value interface{}) error {
	if value == nil {
		ns.CoreRelationshipType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoreRelationshipType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoreRelationshipType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoreRelationshipType), nil
}

type CoreTeamType string

const (
	CoreTeamTypeTRAININGGROUP CoreTeamType = "TRAINING_GROUP"
	CoreTeamTypeSEASONTEAM    CoreTeamType = "SEASON_TEAM"
)

func (e *CoreTeamType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoreTeamType(s)
	case string:
		*e = CoreTeamType(s)
	default:
		return fmt.Errorf("unsupported scan type for CoreTeamType: %T", src)
	}
	return nil
}

type NullCoreTeamType struct {
	CoreTeamType CoreTeamType `json:"core_team_type"`
	Valid        bool         `json:"valid"` // Valid is true if CoreTeamType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoreTeamType) Scan(value interface{}) error {
	if value == nil {
		ns.CoreTeamType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoreTeamType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoreTeamType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoreTeamType), nil
}

type CoreUserRole string

const (
	CoreUserRoleSYSTEMADMIN       CoreUserRole = "SYSTEM_ADMIN"
	CoreUserRoleSUPERADMIN        CoreUserRole = "SUPER_ADMIN"
	CoreUserRoleCLUBADMIN         CoreUserRole = "CLUB_ADMIN"
	CoreUserRoleTECHNICALDIRECTOR CoreUserRole = "TECHNICAL_DIRECTOR"
	CoreUserRoleCOACH             CoreUserRole = "COACH"
	CoreUserRoleGUARDIAN          CoreUserRole = "GUARDIAN"
	CoreUserRolePLAYER            CoreUserRole = "PLAYER"
)

func (e *CoreUserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoreUserRole(s)
	case string:
		*e = CoreUserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for CoreUserRole: %T", src)
	}
	return nil
}

type NullCoreUserRole struct {
	CoreUserRole CoreUserRole `json:"core_user_role"`
	Valid        bool         `json:"valid"` // Valid is true if CoreUserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoreUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.CoreUserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoreUserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoreUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoreUserRole), nil
}

type SchedulingActivityOwnerType string

const (
	SchedulingActivityOwnerTypeTEAM   SchedulingActivityOwnerType = "TEAM"
	SchedulingActivityOwnerTypeROSTER SchedulingActivityOwnerType = "ROSTER"
)

func (e *SchedulingActivityOwnerType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SchedulingActivityOwnerType(s)
	case string:
		*e = SchedulingActivityOwnerType(s)
	default:
		return fmt.Errorf("unsupported scan type for SchedulingActivityOwnerType: %T", src)
	}
	return nil
}

type NullSchedulingActivityOwnerType struct {
	SchedulingActivityOwnerType SchedulingActivityOwnerType `json:"scheduling_activity_owner_type"`
	Valid                       bool                        `json:"valid"` // Valid is true if SchedulingActivityOwnerType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSchedulingActivityOwnerType) Scan(value interface{}) error {
	if value == nil {
		ns.SchedulingActivityOwnerType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SchedulingActivityOwnerType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSchedulingActivityOwnerType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SchedulingActivityOwnerType), nil
}

type SchedulingActivityType string

const (
	SchedulingActivityTypePRACTICE SchedulingActivityType = "PRACTICE"
	SchedulingActivityTypeMATCH    SchedulingActivityType = "MATCH"
)

func (e *SchedulingActivityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SchedulingActivityType(s)
	case string:
		*e = SchedulingActivityType(s)
	default:
		return fmt.Errorf("unsupported scan type for SchedulingActivityType: %T", src)
	}
	return nil
}

type NullSchedulingActivityType struct {
	SchedulingActivityType SchedulingActivityType `json:"scheduling_activity_type"`
	Valid                  bool                   `json:"valid"` // Valid is true if SchedulingActivityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSchedulingActivityType) Scan(value interface{}) error {
	if value == nil {
		ns.SchedulingActivityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SchedulingActivityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSchedulingActivityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SchedulingActivityType), nil
}

type SchedulingWindowType string

const (
	SchedulingWindowTypeSEASON SchedulingWindowType = "SEASON"
	SchedulingWindowTypePOOL   SchedulingWindowType = "POOL"
	SchedulingWindowTypeEVENT  SchedulingWindowType = "EVENT"
)

func (e *SchedulingWindowType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SchedulingWindowType(s)
	case string:
		*e = SchedulingWindowType(s)
	default:
		return fmt.Errorf("unsupported scan type for SchedulingWindowType: %T", src)
	}
	return nil
}

type NullSchedulingWindowType struct {
	SchedulingWindowType SchedulingWindowType `json:"scheduling_window_type"`
	Valid                bool                 `json:"valid"` // Valid is true if SchedulingWindowType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSchedulingWindowType) Scan(value interface{}) error {
	if value == nil {
		ns.SchedulingWindowType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SchedulingWindowType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSchedulingWindowType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SchedulingWindowType), nil
}

// A club, association, or federation — see org_type and parent_club_id for the nesting hierarchy (ADR-008 §6).
type CoreClubs struct {
	ID uuid.UUID `json:"id"`
	// Nullable, self-referencing. A club can belong directly to a federation, or through an intermediate association — nesting depth is unconstrained.
	ParentClubID pgtype.UUID          `json:"parent_club_id"`
	OrgType      CoreOrganizationType `json:"org_type"`
	Name         string               `json:"name"`
	Slug         string               `json:"slug"`
	IsActive     bool                 `json:"is_active"`
	CreatedAt    pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz   `json:"updated_at"`
}

// Junction table mapping parental links and primary contact designations.
type CoreParentsChildren struct {
	ParentID     uuid.UUID            `json:"parent_id"`
	ChildID      uuid.UUID            `json:"child_id"`
	Relationship CoreRelationshipType `json:"relationship"`
	// Flag indicating if this parent should receive primary communications for the child.
	IsPrimaryContact bool               `json:"is_primary_contact"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type CorePlayerPositionPreferences struct {
	PlayerID       uuid.UUID `json:"player_id"`
	PositionID     uuid.UUID `json:"position_id"`
	PreferenceRank int32     `json:"preference_rank"`
}

// Identity records for individual players.
type CorePlayerProfiles struct {
	ID uuid.UUID `json:"id"`
	// Optional link to a dedicated user account if the player logs into the platform directly.
	UserID                pgtype.UUID        `json:"user_id"`
	FirstName             string             `json:"first_name"`
	LastName              string             `json:"last_name"`
	DateOfBirth           pgtype.Date        `json:"date_of_birth"`
	Gender                CoreGenderCategory `json:"gender"`
	MedicalNotes          pgtype.Text        `json:"medical_notes"`
	EmergencyContactName  pgtype.Text        `json:"emergency_contact_name"`
	EmergencyContactPhone *string            `json:"emergency_contact_phone"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type CorePlayerRatings struct {
	PlayerID   uuid.UUID          `json:"player_id"`
	SportID    uuid.UUID          `json:"sport_id"`
	SeasonYear int32              `json:"season_year"`
	Score      int16              `json:"score"`
	UpdatedBy  pgtype.UUID        `json:"updated_by"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Named skill/competitive levels within a pool (e.g., Division 1, Recreational). A roster is formed within one division.
type CorePoolDivisions struct {
	ID     uuid.UUID `json:"id"`
	PoolID uuid.UUID `json:"pool_id"`
	Name   string    `json:"name"`
	Code   string    `json:"code"`
	// Controls the order divisions are listed in (e.g., Division 1 before Division 2).
	DisplayOrder int32              `json:"display_order"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Explicit, per-season registration of a player into a pool (and optionally a specific division).
type CorePoolRegistrations struct {
	ID         uuid.UUID   `json:"id"`
	PlayerID   uuid.UUID   `json:"player_id"`
	PoolID     uuid.UUID   `json:"pool_id"`
	DivisionID pgtype.UUID `json:"division_id"`
	// PENDING at registration; the application sets it to ASSIGNED when the player is added to an active TRAINING_GROUP team in core.team_players. No DB trigger — this is an application-layer responsibility.
	Status       CoreRegistrationStatus `json:"status"`
	RegisteredAt pgtype.Timestamptz     `json:"registered_at"`
	IsActive     bool                   `json:"is_active"`
}

// Age group pools and categories for player registration (e.g., U10F, U12M), scoped to one club. window_id references scheduling.date_windows for actual dates; season_year stays a human label.
type CorePools struct {
	ID       uuid.UUID `json:"id"`
	ClubID   uuid.UUID `json:"club_id"`
	SportID  uuid.UUID `json:"sport_id"`
	WindowID uuid.UUID `json:"window_id"`
	Name     string    `json:"name"`
	// Division short code (e.g., U10F_D1, U12M_LOCAL).
	Code       string             `json:"code"`
	MinAge     int32              `json:"min_age"`
	MaxAge     int32              `json:"max_age"`
	Gender     CoreGenderCategory `json:"gender"`
	SeasonYear int32              `json:"season_year"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type CorePositions struct {
	ID           uuid.UUID          `json:"id"`
	SportID      uuid.UUID          `json:"sport_id"`
	Code         string             `json:"code"`
	Name         string             `json:"name"`
	DisplayOrder int32              `json:"display_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Reference table for multi-sport support abstraction (ADR-004).
type CoreSports struct {
	// Primary key UUID generated via gen_random_uuid().
	ID uuid.UUID `json:"id"`
	// Short code identifier for the sport (e.g., SOCCER, HOCKEY).
	Code                         string `json:"code"`
	Name                         string `json:"name"`
	Slug                         string `json:"slug"`
	DefaultPeriods               int32  `json:"default_periods"`
	DefaultPeriodDurationMinutes int32  `json:"default_period_duration_minutes"`
	// Flexible JSONB storing sport-specific configurations such as roster size rules or match periods.
	RulesConfig []byte             `json:"rules_config"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Team membership — no event scoping (that is tournament.roster_players).
type CoreTeamPlayers struct {
	TeamID    uuid.UUID          `json:"team_id"`
	PlayerID  uuid.UUID          `json:"player_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Pool(s) a team draws players from. Multiple rows is how a season team combines age groups (e.g., U9 + U10).
type CoreTeamPools struct {
	TeamID uuid.UUID `json:"team_id"`
	PoolID uuid.UUID `json:"pool_id"`
}

// Persistent club structure (training group or season team), independent of any tournament/event (ADR-008 §1).
type CoreTeams struct {
	ID      uuid.UUID `json:"id"`
	ClubID  uuid.UUID `json:"club_id"`
	SportID uuid.UUID `json:"sport_id"`
	// References scheduling.date_windows — teams no longer store their own start_date/end_date (ADR-008 §4).
	WindowID   uuid.UUID          `json:"window_id"`
	Type       CoreTeamType       `json:"type"`
	Name       string             `json:"name"`
	SeasonYear int32              `json:"season_year"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Multi-role grants per user. A user can be GUARDIAN and COACH simultaneously; authorization checks the full set, not a single value.
type CoreUserRoles struct {
	ID     uuid.UUID    `json:"id"`
	UserID uuid.UUID    `json:"user_id"`
	ClubID pgtype.UUID  `json:"club_id"`
	Role   CoreUserRole `json:"role"`
	// Default role context shown at login/UI — not an authorization boundary by itself.
	IsPrimary bool               `json:"is_primary"`
	GrantedAt pgtype.Timestamptz `json:"granted_at"`
	GrantedBy pgtype.UUID        `json:"granted_by"`
}

// Platform accounts including administrators, technical directors, coaches, parents, and players. A single account can hold roles across multiple clubs — see core.user_roles.
type CoreUsers struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	Phone        *string            `json:"phone"`
	Role         CoreUserRole       `json:"role"`
	IsActive     bool               `json:"is_active"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// A single practice or match. owner_id is a loose reference (no FK) to core.teams or tournament.rosters, chosen via owner_type — kept loose so scheduling stays a dependency-free kernel.
type SchedulingActivities struct {
	ID         uuid.UUID                   `json:"id"`
	Type       SchedulingActivityType      `json:"type"`
	OwnerType  SchedulingActivityOwnerType `json:"owner_type"`
	OwnerID    uuid.UUID                   `json:"owner_id"`
	FieldID    pgtype.UUID                 `json:"field_id"`
	SubFieldID pgtype.UUID                 `json:"sub_field_id"`
	StartsAt   pgtype.Timestamptz          `json:"starts_at"`
	EndsAt     pgtype.Timestamptz          `json:"ends_at"`
	CreatedAt  pgtype.Timestamptz          `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz          `json:"updated_at"`
}

type SchedulingAttendances struct {
	ActivityID uuid.UUID          `json:"activity_id"`
	PlayerID   uuid.UUID          `json:"player_id"`
	IsPresent  pgtype.Bool        `json:"is_present"`
	RecordedAt pgtype.Timestamptz `json:"recorded_at"`
}

// Canonical start/end date range for a season, a pool, or an event.
type SchedulingDateWindows struct {
	ID        uuid.UUID            `json:"id"`
	Type      SchedulingWindowType `json:"type"`
	Label     string               `json:"label"`
	StartDate pgtype.Date          `json:"start_date"`
	EndDate   pgtype.Date          `json:"end_date"`
	CreatedAt pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt pgtype.Timestamptz   `json:"updated_at"`
}

type SchedulingFields struct {
	ID        uuid.UUID          `json:"id"`
	ClubID    uuid.UUID          `json:"club_id"`
	Name      string             `json:"name"`
	Address   pgtype.Text        `json:"address"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type SchedulingSubFields struct {
	ID        uuid.UUID          `json:"id"`
	FieldID   uuid.UUID          `json:"field_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
