// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pools.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPool = `-- name: CreatePool :one
INSERT INTO core.pools (sport_id, code, name)
VALUES ($1, $2, $3)
RETURNING id, club_id, sport_id, window_id, name, code, min_age, max_age, gender, season_year, is_active, created_at, updated_at
`

type CreatePoolParams struct {
	SportID uuid.UUID `json:"sport_id"`
	Code    string    `json:"code"`
	Name    string    `json:"name"`
}

// CreatePool inserts a new age pool into the club structure.
func (q *Queries) CreatePool(ctx context.Context, arg CreatePoolParams) (CorePools, error) {
	row := q.db.QueryRow(ctx, createPool, arg.SportID, arg.Code, arg.Name)
	var i CorePools
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.SportID,
		&i.WindowID,
		&i.Name,
		&i.Code,
		&i.MinAge,
		&i.MaxAge,
		&i.Gender,
		&i.SeasonYear,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPoolByID = `-- name: GetPoolByID :one
SELECT id, club_id, sport_id, window_id, name, code, min_age, max_age, gender, season_year, is_active, created_at, updated_at FROM core.pools
WHERE id = $1
`

// GetPoolByID retrieves the details of an age pool by its UUID.
func (q *Queries) GetPoolByID(ctx context.Context, id uuid.UUID) (CorePools, error) {
	row := q.db.QueryRow(ctx, getPoolByID, id)
	var i CorePools
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.SportID,
		&i.WindowID,
		&i.Name,
		&i.Code,
		&i.MinAge,
		&i.MaxAge,
		&i.Gender,
		&i.SeasonYear,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
