// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// ----------------------------------------------------------------------------
	// PLAYER PROFILES QUERIES
	// ----------------------------------------------------------------------------
	CreatePlayerProfile(ctx context.Context, arg CreatePlayerProfileParams) (CorePlayerProfiles, error)
	// CreatePool inserts a new age pool into the club structure.
	CreatePool(ctx context.Context, arg CreatePoolParams) (CorePools, error)
	// ============================================================================
	// PROJECT PULSE — Core Module SQL Queries (sqlc)
	// Schema: core
	// Entities: users, player_profiles, parents_children, pools
	// ============================================================================
	// ----------------------------------------------------------------------------
	// USERS QUERIES
	// ----------------------------------------------------------------------------
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetPlayerProfileByID(ctx context.Context, id uuid.UUID) (CorePlayerProfiles, error)
	// GetPoolByID retrieves the details of an age pool by its UUID.
	GetPoolByID(ctx context.Context, id uuid.UUID) (CorePools, error)
	GetUserByEmail(ctx context.Context, email string) (CoreUsers, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (CoreUsers, error)
	// ----------------------------------------------------------------------------
	// PARENTS_CHILDREN RELATIONSHIP QUERIES
	// ----------------------------------------------------------------------------
	LinkParentToChild(ctx context.Context, arg LinkParentToChildParams) error
	ListChildrenByParentID(ctx context.Context, parentID uuid.UUID) ([]ListChildrenByParentIDRow, error)
	// ----------------------------------------------------------------------------
	// POOLS (AGE CATEGORIES) QUERIES
	// ----------------------------------------------------------------------------
	ListPoolsBySportAndSeason(ctx context.Context, arg ListPoolsBySportAndSeasonParams) ([]ListPoolsBySportAndSeasonRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	UnlinkParentFromChild(ctx context.Context, arg UnlinkParentFromChildParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
