// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: teams.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addPlayerToTeam = `-- name: AddPlayerToTeam :exec
INSERT INTO core.team_players (
    team_id,
    player_id
) VALUES (
    $1, $2
)
`

type AddPlayerToTeamParams struct {
	TeamID   uuid.UUID `json:"team_id"`
	PlayerID uuid.UUID `json:"player_id"`
}

func (q *Queries) AddPlayerToTeam(ctx context.Context, arg AddPlayerToTeamParams) error {
	_, err := q.db.Exec(ctx, addPlayerToTeam, arg.TeamID, arg.PlayerID)
	return err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO core.teams (
    club_id,
    sport_id,
    window_id,
    type,
    name,
    season_year
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, club_id, sport_id, window_id, type, name, season_year, created_at, updated_at
`

type CreateTeamParams struct {
	ClubID     uuid.UUID    `json:"club_id"`
	SportID    uuid.UUID    `json:"sport_id"`
	WindowID   uuid.UUID    `json:"window_id"`
	Type       CoreTeamType `json:"type"`
	Name       string       `json:"name"`
	SeasonYear int32        `json:"season_year"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (CoreTeams, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.ClubID,
		arg.SportID,
		arg.WindowID,
		arg.Type,
		arg.Name,
		arg.SeasonYear,
	)
	var i CoreTeams
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.SportID,
		&i.WindowID,
		&i.Type,
		&i.Name,
		&i.SeasonYear,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, club_id, sport_id, window_id, type, name, season_year, created_at, updated_at
FROM core.teams
WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id uuid.UUID) (CoreTeams, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i CoreTeams
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.SportID,
		&i.WindowID,
		&i.Type,
		&i.Name,
		&i.SeasonYear,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkTeamToPool = `-- name: LinkTeamToPool :exec
INSERT INTO core.team_pools (
    team_id,
    pool_id
) VALUES (
    $1, $2
)
`

type LinkTeamToPoolParams struct {
	TeamID uuid.UUID `json:"team_id"`
	PoolID uuid.UUID `json:"pool_id"`
}

func (q *Queries) LinkTeamToPool(ctx context.Context, arg LinkTeamToPoolParams) error {
	_, err := q.db.Exec(ctx, linkTeamToPool, arg.TeamID, arg.PoolID)
	return err
}

const listTeamPlayerIDs = `-- name: ListTeamPlayerIDs :many
SELECT player_id
FROM core.team_players
WHERE team_id = $1
`

func (q *Queries) ListTeamPlayerIDs(ctx context.Context, teamID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listTeamPlayerIDs, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var player_id uuid.UUID
		if err := rows.Scan(&player_id); err != nil {
			return nil, err
		}
		items = append(items, player_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamPoolIDs = `-- name: ListTeamPoolIDs :many
SELECT pool_id
FROM core.team_pools
WHERE team_id = $1
`

func (q *Queries) ListTeamPoolIDs(ctx context.Context, teamID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listTeamPoolIDs, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var pool_id uuid.UUID
		if err := rows.Scan(&pool_id); err != nil {
			return nil, err
		}
		items = append(items, pool_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByClub = `-- name: ListTeamsByClub :many
SELECT id, club_id, sport_id, window_id, type, name, season_year, created_at, updated_at
FROM core.teams
WHERE club_id = $1
ORDER BY name ASC
LIMIT $2 OFFSET $3
`

type ListTeamsByClubParams struct {
	ClubID uuid.UUID `json:"club_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListTeamsByClub(ctx context.Context, arg ListTeamsByClubParams) ([]CoreTeams, error) {
	rows, err := q.db.Query(ctx, listTeamsByClub, arg.ClubID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreTeams
	for rows.Next() {
		var i CoreTeams
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.SportID,
			&i.WindowID,
			&i.Type,
			&i.Name,
			&i.SeasonYear,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePlayerFromTeam = `-- name: RemovePlayerFromTeam :exec
DELETE FROM core.team_players
WHERE team_id = $1 AND player_id = $2
`

type RemovePlayerFromTeamParams struct {
	TeamID   uuid.UUID `json:"team_id"`
	PlayerID uuid.UUID `json:"player_id"`
}

func (q *Queries) RemovePlayerFromTeam(ctx context.Context, arg RemovePlayerFromTeamParams) error {
	_, err := q.db.Exec(ctx, removePlayerFromTeam, arg.TeamID, arg.PlayerID)
	return err
}
