// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPlayerProfile = `-- name: CreatePlayerProfile :one

INSERT INTO core.player_profiles (
    user_id,
    first_name,
    last_name,
    date_of_birth,
    gender,
    medical_notes,
    emergency_contact_name,
    emergency_contact_phone
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, user_id, first_name, last_name, date_of_birth, gender, medical_notes, emergency_contact_name, emergency_contact_phone, created_at, updated_at
`

type CreatePlayerProfileParams struct {
	UserID                pgtype.UUID        `json:"user_id"`
	FirstName             string             `json:"first_name"`
	LastName              string             `json:"last_name"`
	DateOfBirth           pgtype.Date        `json:"date_of_birth"`
	Gender                CoreGenderCategory `json:"gender"`
	MedicalNotes          pgtype.Text        `json:"medical_notes"`
	EmergencyContactName  pgtype.Text        `json:"emergency_contact_name"`
	EmergencyContactPhone *string            `json:"emergency_contact_phone"`
}

// ----------------------------------------------------------------------------
// PLAYER PROFILES QUERIES
// ----------------------------------------------------------------------------
func (q *Queries) CreatePlayerProfile(ctx context.Context, arg CreatePlayerProfileParams) (CorePlayerProfiles, error) {
	row := q.db.QueryRow(ctx, createPlayerProfile,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.DateOfBirth,
		arg.Gender,
		arg.MedicalNotes,
		arg.EmergencyContactName,
		arg.EmergencyContactPhone,
	)
	var i CorePlayerProfiles
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Gender,
		&i.MedicalNotes,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one


INSERT INTO core.users (
    email,
    password_hash,
    first_name,
    last_name,
    phone,
    role
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, email, first_name, last_name, phone, role, is_active, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	FirstName    string       `json:"first_name"`
	LastName     string       `json:"last_name"`
	Phone        *string      `json:"phone"`
	Role         CoreUserRole `json:"role"`
}

type CreateUserRow struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	Phone       *string            `json:"phone"`
	Role        CoreUserRole       `json:"role"`
	IsActive    bool               `json:"is_active"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// ============================================================================
// PROJECT PULSE — Core Module SQL Queries (sqlc)
// Schema: core
// Entities: users, player_profiles, parents_children, pools
// ============================================================================
// ----------------------------------------------------------------------------
// USERS QUERIES
// ----------------------------------------------------------------------------
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM core.users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getPlayerProfileByID = `-- name: GetPlayerProfileByID :one
SELECT id, user_id, first_name, last_name, date_of_birth, gender, medical_notes, emergency_contact_name, emergency_contact_phone, created_at, updated_at
FROM core.player_profiles
WHERE id = $1
`

func (q *Queries) GetPlayerProfileByID(ctx context.Context, id uuid.UUID) (CorePlayerProfiles, error) {
	row := q.db.QueryRow(ctx, getPlayerProfileByID, id)
	var i CorePlayerProfiles
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Gender,
		&i.MedicalNotes,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, first_name, last_name, phone, role, is_active, last_login_at, created_at, updated_at
FROM core.users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (CoreUsers, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i CoreUsers
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, first_name, last_name, phone, role, is_active, last_login_at, created_at, updated_at
FROM core.users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (CoreUsers, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i CoreUsers
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkParentToChild = `-- name: LinkParentToChild :exec

INSERT INTO core.parents_children (
    parent_id,
    child_id,
    relationship,
    is_primary_contact
) VALUES (
    $1, $2, $3, $4
) ON CONFLICT (parent_id, child_id) DO UPDATE
SET relationship = EXCLUDED.relationship,
    is_primary_contact = EXCLUDED.is_primary_contact
`

type LinkParentToChildParams struct {
	ParentID         uuid.UUID            `json:"parent_id"`
	ChildID          uuid.UUID            `json:"child_id"`
	Relationship     CoreRelationshipType `json:"relationship"`
	IsPrimaryContact bool                 `json:"is_primary_contact"`
}

// ----------------------------------------------------------------------------
// PARENTS_CHILDREN RELATIONSHIP QUERIES
// ----------------------------------------------------------------------------
func (q *Queries) LinkParentToChild(ctx context.Context, arg LinkParentToChildParams) error {
	_, err := q.db.Exec(ctx, linkParentToChild,
		arg.ParentID,
		arg.ChildID,
		arg.Relationship,
		arg.IsPrimaryContact,
	)
	return err
}

const listChildrenByParentID = `-- name: ListChildrenByParentID :many
SELECT p.id, p.user_id, p.first_name, p.last_name, p.date_of_birth, p.gender, pc.relationship, pc.is_primary_contact
FROM core.player_profiles p
JOIN core.parents_children pc ON p.id = pc.child_id
WHERE pc.parent_id = $1
ORDER BY p.date_of_birth DESC
`

type ListChildrenByParentIDRow struct {
	ID               uuid.UUID            `json:"id"`
	UserID           pgtype.UUID          `json:"user_id"`
	FirstName        string               `json:"first_name"`
	LastName         string               `json:"last_name"`
	DateOfBirth      pgtype.Date          `json:"date_of_birth"`
	Gender           CoreGenderCategory   `json:"gender"`
	Relationship     CoreRelationshipType `json:"relationship"`
	IsPrimaryContact bool                 `json:"is_primary_contact"`
}

func (q *Queries) ListChildrenByParentID(ctx context.Context, parentID uuid.UUID) ([]ListChildrenByParentIDRow, error) {
	rows, err := q.db.Query(ctx, listChildrenByParentID, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChildrenByParentIDRow
	for rows.Next() {
		var i ListChildrenByParentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.DateOfBirth,
			&i.Gender,
			&i.Relationship,
			&i.IsPrimaryContact,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoolsBySportAndSeason = `-- name: ListPoolsBySportAndSeason :many

SELECT id, sport_id, name, code, min_age, max_age, gender, season_year, is_active
FROM core.pools
WHERE sport_id = $1 AND season_year = $2 AND is_active = true
ORDER BY min_age ASC, code ASC
`

type ListPoolsBySportAndSeasonParams struct {
	SportID    uuid.UUID `json:"sport_id"`
	SeasonYear int32     `json:"season_year"`
}

type ListPoolsBySportAndSeasonRow struct {
	ID         uuid.UUID          `json:"id"`
	SportID    uuid.UUID          `json:"sport_id"`
	Name       string             `json:"name"`
	Code       string             `json:"code"`
	MinAge     int32              `json:"min_age"`
	MaxAge     int32              `json:"max_age"`
	Gender     CoreGenderCategory `json:"gender"`
	SeasonYear int32              `json:"season_year"`
	IsActive   bool               `json:"is_active"`
}

// ----------------------------------------------------------------------------
// POOLS (AGE CATEGORIES) QUERIES
// ----------------------------------------------------------------------------
func (q *Queries) ListPoolsBySportAndSeason(ctx context.Context, arg ListPoolsBySportAndSeasonParams) ([]ListPoolsBySportAndSeasonRow, error) {
	rows, err := q.db.Query(ctx, listPoolsBySportAndSeason, arg.SportID, arg.SeasonYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPoolsBySportAndSeasonRow
	for rows.Next() {
		var i ListPoolsBySportAndSeasonRow
		if err := rows.Scan(
			&i.ID,
			&i.SportID,
			&i.Name,
			&i.Code,
			&i.MinAge,
			&i.MaxAge,
			&i.Gender,
			&i.SeasonYear,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, first_name, last_name, phone, role, is_active, created_at
FROM core.users
ORDER BY last_name ASC, first_name ASC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Phone     *string            `json:"phone"`
	Role      CoreUserRole       `json:"role"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkParentFromChild = `-- name: UnlinkParentFromChild :exec
DELETE FROM core.parents_children
WHERE parent_id = $1 AND child_id = $2
`

type UnlinkParentFromChildParams struct {
	ParentID uuid.UUID `json:"parent_id"`
	ChildID  uuid.UUID `json:"child_id"`
}

func (q *Queries) UnlinkParentFromChild(ctx context.Context, arg UnlinkParentFromChildParams) error {
	_, err := q.db.Exec(ctx, unlinkParentFromChild, arg.ParentID, arg.ChildID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE core.users
SET
    first_name = COALESCE($2, first_name),
    last_name = COALESCE($3, last_name),
    phone = COALESCE($4, phone),
    role = COALESCE($5::core.user_role, role),
    is_active = COALESCE($6, is_active),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, email, first_name, last_name, phone, role, is_active, updated_at
`

type UpdateUserParams struct {
	ID        uuid.UUID    `json:"id"`
	FirstName string       `json:"first_name"`
	LastName  string       `json:"last_name"`
	Phone     *string      `json:"phone"`
	Column5   CoreUserRole `json:"column_5"`
	IsActive  bool         `json:"is_active"`
}

type UpdateUserRow struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Phone     *string            `json:"phone"`
	Role      CoreUserRole       `json:"role"`
	IsActive  bool               `json:"is_active"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Column5,
		arg.IsActive,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE core.users
SET last_login_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}
